### ISSUE TITLE
Black screen in some browsers

### ISSUE THREAD

**Issue by polymorphicengine** [hydra-synth/hydra-synth#32] opened 2019-12-10 14:15 UTC
When opening https://hydra-editor.glitch.me/ with microsoft edge there appears only a black screen. The error the console gives me is: 

SCRIPT438: SCRIPT438: Object doesn't support property or method 'captureStream' bundle.js (22526,7)

I know this issue exists also on some browsers on mobile phones, didn't check myself though.

**Comment by micuat** [comment] 2020-12-07 12:41
it works on my windows' edge - unless more details are given (what version of the operating system / browser etc) should we close the issue? @ojack

**Comment by zachkrall** [comment] 2022-04-04 19:45
@micuat this might have been fixed with #79 ?

**Comment by micuat** [comment] 2022-04-04 20:33
it could be. and I don't think the issue is relevant anymore - if anyone finds this issue, please reopen or open a new issue

**Closed by micuat** 2022-04-04 20:33 UTC
